// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string,arg2:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetTasks():Promise<Array<main.Task>>;

export function UpdateTask(arg1:number,arg2:boolean,arg3:string,arg4:number):Promise<void>;
